# regression task settings


name: regression
task_class:
  _target_: src.tasks.standard_task.StandardTask
output_dim: 1
metric_type: regression

# which metric determins early stopping/checkpointing
monitor_metric: null
monitor_mode: max

# loss function
loss_fn:
  _target_: torch.nn.MSELoss
  reduction: mean
